# 网站的基本信息
site:
  tab: Eser SEVİNÇ # Tarayıcı sekme çubuğu görüntülenir
  title: Eser SEVİNÇ # Web sitesinin başlığı
  description: Yazılım sektöründe; İş Analizi, Proje Yönetimi, Ekip Yönetimi ve Liderlik gibi konular üzerine bilgi birikimi. # SEO vb. amaçlarla kullanılan sitenin tanımı.
  language: tr # Web sitesinin dili, örneğin "en" İngilizce
  favicon: /favicon.ico # Tarayıcı sekmelerinde ve diğer yerlerde kullanılan web sitesinin simgesi
  theme: # Daha fazla tema için https://daisyui.com/docs/themes/
    light: cupcake # Açık mod
    dark:  halloween # Koyu mod
    code: andromeeda # Kod bloğunun teması https://shiki.style/themes
  date_format: ddd DD MMM YYYY # Tarih biçimi ayarı, özel biçimi destekler
  blog: # Blog ile ilgili yapılandırma
    pageSize: 7 # Sayfa başına görüntülenecek makale sayısı
  menu: # Menü yapılandırması
    - id: home # Öğe için benzersiz tanımlayıcı
      text: Anasayfa # Menü öğesi görüntüleme
      href: / # Menü öğesi bağlantısının URL'si
      svg: "material-symbols:home-outline-rounded"
      target: _self
    - id: about
      text: Hakkımda
      href: /about
      svg: "material-symbols:info-outline-rounded"
      target: _self
    - id: blog
      text: Blog
      href: /blog
      svg: "material-symbols:book-2-outline-rounded"
      target: _self
    - id: project
      text: Projeler
      href: /project
      svg: "material-symbols:code-blocks-outline"
      target: _self
    - id: friend
      text: Blogroll
      href: /friend
      svg: "material-symbols:supervisor-account-outline-rounded"
      target: _self
    - id: contact
      text: İletişim
      href: /contact
      target: _self
      svg: "material-symbols:attach-email-outline-rounded"

# Kullanıcının Kişisel Bilgileri
user:
  name: Eser Sevinç # kullanıcı adı
  site: "https://esersevinc.com.tr" # Kullanıcının web sitesi bağlantısı
  avatar: /ESLOGO.png # Kullanıcı avatar yolu
  sidebar: # Kenar Çubuğu Yapılandırması
    social:
      - href: "https://mastodon.social/@esersevinc" # Bağlantı
        ariaLabel: Mastodon # Simgeler için erişilebilirlik etiketleri
        title: Mastodon # Simge yüzen başlık
        svg: "ri:mastodon-line"
      - href: "https://github.com/Eser360"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://www.strava.com/athletes/esersevinc/"
        ariaLabel: Strava
        title: Strava
        svg: "ri:riding-line"
      - href: "https://esersevinc.com.tr/rss.xml"
        ariaLabel: RSS
        title: RSS
        svg: "ri:rss-line"
  footer:
    social:
      - href: "https://mastodon.social/@esersevinc"
        ariaLabel: Mastodon
        title: Mastodon
        svg: "ri:mastodon-line"
      - href: "https://github.com/Eser360"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://pixelfed.social/Eser"
        ariaLabel: Pixelfed
        title: Pixelfed
        svg: "ri:pixelfed-line"
      - href: "https://www.strava.com/athletes/esersevinc/"
        ariaLabel: Strava
        title: Strava
        svg: "ri:riding-line"
